%% Script for Preparing Marker Data
clear 
home
tic
% Load OpenSim libs
import org.opensim.modeling.*

forceRepresentation = 1;
markerFile = 1;
grfFile = 1;
%-------------------------------------------
% Make list of file paths to loop through
%-------------------------------------------
processAllTrialsInFolder = 1;
Folder = 'G:\My Drive\Research\AgingPilotsAnalysis\OpenSim\Practice\YAPilot15\c3dFiles\';

if processAllTrialsInFolder
    cd(Folder)
    fileList = strip(string(ls));
    fileList = unique(extractBefore(fileList(3:end,:), '.')); % gets rid of '.' and '..' generated by ls and removes duplicates
else
    disp('no option to use subset of files yet')
    keyboard        % haven't created an option for if you don't want to use all files
end
cd('C:\Users\Hannah\Documents\GitHub\NeuroMobLab_Allen\AgingProject\OpenSim\')
%-------------------------------------------
% Loop through c3d files
%-------------------------------------------
for iFile = 2:numel(fileList)
    filename = [char(fileList(iFile)) '.c3d'];
%     c3dpath = [Folder filename '.c3d']
    
    createOSIMInputFilesVICON_NeuroMobLab(forceRepresentation, markerFile, grfFile, Folder, filename);
    
end
clear iFile
toc
beep